### ISSUE TITLE
Add linting tool to the project

### ISSUE THREAD

**Issue by Guribeiro** [ericksvaguilar/moveit-next#1]
### How about add eslint + prettier to this project ? 

Using tools like these we can make sure the people with access to the code are following a certain patter and rules.

[here's a post where you can read more about it](https://medium.com/cwi-software/eslint-prettier-a-dupla-perfeita-para-produtividade-e-padroniza%C3%A7%C3%A3o-de-c%C3%B3digo-6a7730cfa358)

**Comment by ericksvaguilar** [comment]
That's a good idea!

**Comment by ericksvaguilar** [comment]
@Guribeiro I already merge your pull request #2 to follow these patterns and rules, thanks for collaborate 🙏
